### ISSUE TITLE
Persist cascade state when navigating pages

### ISSUE THREAD

**Issue by cabishop** [iscoe/dragonfly#19]
Persist cascade state when navigating pages. Currently, if you turn off the cascade and then move to the next page - the cascade will reset back to on automatically.

**Comment by cash** [comment]
So I solved this by adding two cascade settings: a per page cascade setting that can be toggled with the checkbox and a default cascade setting controlled through the Settings dialog. Each page starts with the default but can be toggled as needed for that page without affecting the starting point.

9760247467f17966bd0d0d3ea7ab54761bfc1c36
