### ISSUE TITLE
.anno files duplicated in wrong place

### ISSUE THREAD

**Issue by jamesmayfield** [iscoe/dragonfly#45]
On completion of a set I found more .anno files than there were source files. Two .anno files were duplicated from a set I had previously been annotating. The files were identical. I'm not sure how to reproduce the problem, but it has something to do with leaving the Web interface open while shutting down the server and restarting it on a different data set.

**Comment by cash** [comment]
If you have auto save on and have multiple tabs open with dragonfly and restart the server on a different dataset, the tabs will keep trying to auto save to the new dragonfly instance. The fix would be confirming a doc_id belongs to the set that is being saved.
